######################### server ##########################
server:
  port: 8080
############################ Spring 数据源配置 ##########################
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 本地数据库
    url: jdbc:mysql://localhost:3306/z_reader?serverTimezone=Asia/Shanghai&useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8
    username: root
    password: abc123
    # 连接池配置 HikariCP
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      maximum-pool-size: 20   # 最大连接数
      minimum-idle: 5       # 最小空闲连接数
      connection-timeout: 30000 # (30秒) 获取连接的超时时间
      idle-timeout: 600000    # (10分钟) 连接最大空闲时间