######################### spring ##########################
spring:
  application:
    name: z-reader
  profiles:
    active: test
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB
################### mybatis-plus #########################
mybatis-plus:
  configuration:
    # 驼峰命名映射
    map-underscore-to-camel-case: true